name: Cypress Tests
on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # if you want to enable parallelization
  # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

concurrency:
  group: cypress-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cy-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v6.7.7
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
